[package]
name = "demo_embeddings"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
dotenv = "0.15"
openai = "1.0.0-alpha.13"
polars = "0.32"
serde_json = "1"
tiktoken-rs = "0.5"
tokio = { version = "1.32.0", features = ["full"] }
